-- max ammo allowed to transfer between players
SharedData.MaxAmmo    = {
    AMMO_PISTOL = 100,
    AMMO_PISTOL_EXPRESS = 100,
    AMMO_PISTOL_EXPRESS_EXPLOSIVE = 100,
    AMMO_PISTOL_HIGH_VELOCITY = 100,
    AMMO_PISTOL_SPLIT_POINT = 100,
    AMMO_REPEATER = 100,
    AMMO_REPEATER_EXPRESS = 100,
    AMMO_REPEATER_EXPRESS_EXPLOSIVE = 100,
    AMMO_REPEATER_HIGH_VELOCITY = 100,
    AMMO_REPEATER_SPLIT_POINT = 100,
    AMMO_REVOLVER = 100,
    AMMO_REVOLVER_EXPRESS = 100,
    AMMO_REVOLVER_EXPRESS_EXPLOSIVE = 100,
    AMMO_REVOLVER_HIGH_VELOCITY = 100,
    AMMO_REVOLVER_SPLIT_POINT = 100,
    AMMO_RIFLE = 100,
    AMMO_RIFLE_ELEPHANT = 100,
    AMMO_RIFLE_EXPRESS = 100,
    AMMO_RIFLE_EXPRESS_EXPLOSIVE = 100,
    AMMO_RIFLE_HIGH_VELOCITY = 100,
    AMMO_RIFLE_SPLIT_POINT = 100,
    AMMO_22 = 100,
    AMMO_22_TRANQUILIZER = 100,
    AMMO_SHOTGUN = 100,
    AMMO_SHOTGUN_BUCKSHOT_INCENDIARY = 100,
    AMMO_SHOTGUN_SLUG_EXPLOSIVE = 100,
    AMMO_SHOTGUN_SLUG = 100,
    AMMO_ARROW = 10,
    AMMO_ARROW_DYNAMITE = 10,
    AMMO_ARROW_FIRE = 10,
    AMMO_ARROW_IMPROVED = 10,
    AMMO_ARROW_SMALL_GAME = 10,
    AMMO_ARROW_POISON = 10,
    AMMO_THROWING_KNIVES = 10,
    AMMO_TOMAHAWK = 10,
    AMMO_POISONBOTTLE = 10,
    AMMO_BOLAS = 10,
    AMMO_BOLAS_HAWKMOTH = 10,
    AMMO_BOLAS_INTERTWINED = 10,
    AMMO_BOLAS_IRONSPIKED = 10,
    AMMO_DYNAMITE = 5,
    AMMO_DYNAMITE_VOLATILE = 5,
    AMMO_MOLOTOV = 5,
    AMMO_MOLOTOV_VOLATILE = 5,
    AMMO_HATCHET_CLEAVER = 10,
    AMMO_HATCHET_HUNTER = 10,
    AMMO_HATCHET_DOUBLE_BIT = 10,
    AMMO_HATCHET_HEWING = 10,
    AMMO_HATCHET_VIKING = 10,
    AMMO_HATCHET = 10,
}

-- you can change this to your language
SharedData.AmmoLabels = {

    AMMO_PISTOL = "Pistolen Munition (Normal)",
    AMMO_PISTOL_EXPRESS = "Pistolen Munition (Express)",
    AMMO_PISTOL_EXPRESS_EXPLOSIVE = "Pistolen Munition (Explosiv)",
    AMMO_PISTOL_HIGH_VELOCITY = "Pistolen Munition (Velocity)",
    AMMO_PISTOL_SPLIT_POINT = "Pistolen Munition (Splitpoint)",
    AMMO_REPEATER = "Repeater Muniton (Normal)",
    AMMO_REPEATER_EXPRESS = "Repeater Muniton (Express)",
    AMMO_REPEATER_EXPRESS_EXPLOSIVE = "Repeater Muniton (Explosiv)",
    AMMO_REPEATER_HIGH_VELOCITY = "Repeater Muniton (Velocity)",
    AMMO_REPEATER_SPLIT_POINT = "Repeater Muniton (Splitpoint)",
    AMMO_REVOLVER = "Revolver Munition (Normal)",
    AMMO_REVOLVER_EXPRESS = "Revolver Munition (Express)",
    AMMO_REVOLVER_EXPRESS_EXPLOSIVE = "Revolver Munition (Explosiv)",
    AMMO_REVOLVER_HIGH_VELOCITY = "Revolver Munition (Velocity)",
    AMMO_REVOLVER_SPLIT_POINT = "Revolver Munition (Splitpoint)",
    AMMO_RIFLE = "Gewehr Munition (Normal)",
    AMMO_RIFLE_ELEPHANT = "Gewehr Munition (Elephanten)",
    AMMO_RIFLE_EXPRESS = "Gewehr Munition (Express)",
    AMMO_RIFLE_EXPRESS_EXPLOSIVE = "Gewehr Munition (Explosiv)",
    AMMO_RIFLE_HIGH_VELOCITY = "Gewehr Munition (Velocity)",
    AMMO_RIFLE_SPLIT_POINT = "Gewehr Munition (Splitpoint)",
    AMMO_22 = "Varmint Munition (Normal)",
    AMMO_22_TRANQUILIZER = "Varmint Munition (Betäubungsmittel)",
    AMMO_SHOTGUN = "Schrottflinten Munition (Normal)",
    AMMO_SHOTGUN_BUCKSHOT_INCENDIARY = "Schrottflinte Munition (Brand)",
    AMMO_SHOTGUN_SLUG_EXPLOSIVE = "Schrottflinte Munition (Explosiv)",
    AMMO_SHOTGUN_SLUG = "Schrottflinte Munition (Slug)",
    AMMO_ARROW = "Pfeile (Normal)",
    AMMO_ARROW_DYNAMITE = "Pfeile (Normal)",
    AMMO_ARROW_FIRE = "Pfeile (Feuer)",
    AMMO_ARROW_IMPROVED = "Pfeile (Verbessert)",
    AMMO_ARROW_SMALL_GAME = "Pfeile (Kleintier)",
    AMMO_ARROW_POISON = "Pfeile (Gift)",
    AMMO_THROWING_KNIVES = "Wurfmesser",
    AMMO_TOMAHAWK = "Tomahawk",
    AMMO_POISONBOTTLE = "Giftflasche",
    AMMO_BOLAS = "Bolas",
    AMMO_BOLAS_HAWKMOTH = "Hawkmoth Bolas",
    AMMO_BOLAS_INTERTWINED = "Gewundene Bolas",
    AMMO_BOLAS_IRONSPIKED = "Eisen Bolas",
    AMMO_DYNAMITE = "Dynamite",
    AMMO_DYNAMITE_VOLATILE = 'Volatile Dynamite',
    AMMO_MOLOTOV = "Molotov",
    AMMO_MOLOTOV_VOLATILE = "Volatile Molotov",
    AMMO_HATCHET_CLEAVER = "Hackebeil",
    AMMO_HATCHET_HUNTER = "Jagdacht",
    AMMO_HATCHET_DOUBLE_BIT = "Doppelklingen Axt",
    AMMO_HATCHET_HEWING = "Schlag Axt",
    AMMO_HATCHET_VIKING = "Wikinger Axt",
    AMMO_HATCHET = "Wurfäxte",
}

-- dont touch this
SharedData.AmmoTypes  = {
    [416676503] = {
        "AMMO_PISTOL",
        "AMMO_PISTOL_EXPRESS",
        "AMMO_PISTOL_EXPRESS_EXPLOSIVE",
        "AMMO_PISTOL_HIGH_VELOCITY",
        "AMMO_PISTOL_SPLIT_POINT"
    },
    [-594562071] = {
        "AMMO_REPEATER",
        "AMMO_REPEATER_EXPRESS",
        "AMMO_REPEATER_EXPRESS_EXPLOSIVE",
        "AMMO_REPEATER_HIGH_VELOCITY",
        "AMMO_REPEATER_SPLIT_POINT"
    },
    [-1101297303] = {
        "AMMO_REVOLVER",
        "AMMO_REVOLVER_EXPRESS",
        "AMMO_REVOLVER_EXPRESS_EXPLOSIVE",
        "AMMO_REVOLVER_HIGH_VELOCITY",
        "AMMO_REVOLVER_SPLIT_POINT",
        "AMMO_SHOTGUN",
        "AMMO_SHOTGUN_BUCKSHOT_INCENDIARY",
        "AMMO_SHOTGUN_SLUG_EXPLOSIVE",
        "AMMO_SHOTGUN_SLUG"
    },
    [970310034] = { "AMMO_RIFLE",
        "AMMO_RIFLE_ELEPHANT",
        "AMMO_RIFLE_EXPRESS",
        "AMMO_RIFLE_EXPRESS_EXPLOSIVE",
        "AMMO_RIFLE_HIGH_VELOCITY",
        "AMMO_RIFLE_SPLIT_POINT",
        "AMMO_22", "AMMO_22_TRANQUILIZER"
    },
    [-1212426201] = { "AMMO_RIFLE",
        "AMMO_RIFLE_EXPRESS",
        "AMMO_RIFLE_EXPRESS_EXPLOSIVE",
        "AMMO_RIFLE_HIGH_VELOCITY",
        "AMMO_RIFLE_SPLIT_POINT"
    },
    [860033945] = { "AMMO_SHOTGUN",
        "AMMO_SHOTGUN_BUCKSHOT_INCENDIARY",
        "AMMO_SHOTGUN_SLUG_EXPLOSIVE",
        "AMMO_SHOTGUN_SLUG"
    },
    [-1241684019] = { "AMMO_ARROW",
        "AMMO_ARROW_DYNAMITE",
        "AMMO_ARROW_FIRE",
        "AMMO_ARROW_IMPROVED",
        "AMMO_ARROW_SMALL_GAME",
        "AMMO_ARROW_POISON"
    },
    [1548507267] = {
        "AMMO_THROWING_KNIVES",
        "AMMO_TOMAHAWK",
        "AMMO_POISONBOTTLE",
        "AMMO_BOLAS",
        "AMMO_BOLAS_HAWKMOTH",
        "AMMO_BOLAS_INTERTWINED",
        "AMMO_BOLAS_IRONSPIKED",
        "AMMO_DYNAMITE",
        "AMMO_DYNAMITE_VOLATILE",
        "AMMO_MOLOTOV",
        "AMMO_MOLOTOV_VOLATILE"
    },
    [-1188697038] = {
        "AMMO_HATCHET_CLEAVER",

    },
    [446901936] = {
        "AMMO_HATCHET_HUNTER",
        "AMMO_HATCHET_DOUBLE_BIT",
        "AMMO_HATCHET_HEWING",
        "AMMO_HATCHET_VIKING",
        "AMMO_HATCHET",
    }
}
